# =============================================
# BUILD CONFIG
# =============================================

# Dest config
root:             _lesscss.net
dest:             <%= site.root %>

# Source config
assets:           assets

# Data
data:             data
date:             <%= new Date() %>

# Styles
styles:           styles

# Content
content:          content_zh

# Templates
templates:        templates
pages:            <%= site.templates %>
includes:         <%= site.templates %>/includes
layouts:          <%= site.templates %>/layouts
markedtemplates:  <%= site.templates %>/marked
layoutext:        .hbs
layout:           default

# Extensions
helpers:          <%= site.templates %>/helpers
plugins:
  - assemble-contrib-permalinks
  - templates/plugins/toc.js
  - templates/plugins/holder-404-avoid.js
#  - templates/plugins/link-checker.js

# Less.js metadata
current_version:   <%= less.version %>

# Site metadata
brand:             lesscss.net
title:             Less.js
lead:              Less « 动态样式语言
description: >
  Less为CSS添加了动态特性，如变量、混合、运算、函数等。
  Less既可以在服务端编译（Node.js或者Rhino），也可以在客户端编译（现代浏览器）。

# URLs
homepage:          http://lesscss.net
repo:              <%= pkg.repository.url %>
issues:            <%= pkg.bugs.url %>?&state=open
download:
  source:          <%= pkg.homepages %>/archive/master.zip
  latest:          https://raw.github.com/less/less.js/master/dist/less-<%= less.version %>.min.js

cdn:
  cloudflare:      //cdnjs.cloudflare.com/ajax/libs/less.js/

# SEO/SEM
analytics:
  alexa:           false
  google:          false
  google_site_id:  false


# Comments
disqus:
  enabled:        false
  shortname:      <%= pkg.name %>

# Social
social:
  twitter:
    via:          false
    username:     false
  facebook:       false
  linkedin:       false
  gplus:          false
  hn:             false
  google:         false

# Sharing
sharing:
  twitter:        false
  facebook:       false
  gplus:          false
  hn:             false
  google:         false
